AdditionalResourcesPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Action:
          - 'dynamodb:BatchGet*'
          - 'dynamodb:DescribeStream'
          - 'dynamodb:DescribeTable'
          - 'dynamodb:Get*'
          - 'dynamodb:Query'
          - 'dynamodb:Scan'
          - 'dynamodb:BatchWrite*'
          - 'dynamodb:CreateTable'
          - 'dynamodb:Delete*'
          - 'dynamodb:Update*'
          - 'dynamodb:PutItem'
          Resource: !Sub 'arn:aws:dynamodb:*:*:Table/${Project}-${Env}-${App}-dog-table'