DogTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: !Sub ${Project}-${Env}-${App}-dog-table
    AttributeDefinitions: 
      - AttributeName: "dog-name"
        AttributeType: "S"
      - AttributeName: "timestamp"
        AttributeType: "N"
    KeySchema: 
      - AttributeName: "dog-name"
        KeyType: "HASH"
      - AttributeName: "timestamp"
        KeyType: "RANGE"
    BillingMode: "PAY_PER_REQUEST"
