AdditionalResourcesPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Action:
          - 'dynamodb:BatchGet*'
          Resource: !Sub 'arn:aws:dynamodb:*:*:Table/${Project}-${Env}-${App}-dog-table'
