AdditionalResourcesPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
      - Effect: Allow
        Action:
        - "dynamodb:BatchGet*"
        - "dynamodb:DescribeStream"
        - "dynamodb:DescribeTable"
        - "dynamodb:Get*"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:BatchWrite*"
        - "dynamodb:CreateTable"
        - "dynamodb:Delete*"
        - "dynamodb:Update*"
        - "dynamodb:PutItem"
        Resource: !Sub
        - "arn:aws:dynamodb:*:*:table/${Table}"
        - { Table: !Ref dog-table }
      Statement:
        - Sid: copilot-s3-object-actions
          Action:
            - s3:DeleteObject
            - s3:GetObject
            - s3:PutObject
            - s3:PutObjectACL
            - s3:PutObjectTagging
            - s3:RestoreObject
          Effect: Allow
          Resource: !Sub
          - "arn:aws:s3:::${Bucket}/*"
          - { Bucket: !Ref dog-pic-bucket }
      Statement:
        - Sid: copilot-s3-bucket-actions
          Action:
            - s3:ListBucket
          Effect: Allow
          Resource: !Sub
          - "arn:aws:s3:::${Bucket}"
          - { Bucket: !Ref dog-pic-bucket }