AdditionalResourcesPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    PolicyDocument:
      Version: 2012-10-17
      - Statement:
          Effect: Allow
          Action:
          - "dynamodb:BatchGet*"
          - "dynamodb:DescribeStream"
          - "dynamodb:DescribeTable"
          - "dynamodb:Get*"
          - "dynamodb:Query"
          - "dynamodb:Scan"
          - "dynamodb:BatchWrite*"
          - "dynamodb:CreateTable"
          - "dynamodb:Delete*"
          - "dynamodb:Update*"
          - "dynamodb:PutItem"
          Resource: !GetAtt dogTable.Arn
      - Statement:
          Sid: copilotS3ObjectActions
          Action:
            - s3:DeleteObject
            - s3:GetObject
            - s3:PutObject
            - s3:PutObjectACL
            - s3:PutObjectTagging
            - s3:RestoreObject
          Effect: Allow
          Resource: !Sub
          - "${Bucket}/*"
          - { Bucket: !GetAtt dogPicBucket.Arn }
      - Statement:
          Sid: copilottS3BucketActions
          Action:
            - s3:ListBucket
          Effect: Allow
          Resource: !GetAtt dogPicBucket.Arn